### ISSUE TITLE
Block LOC extension

### ISSUE THREAD

**Issue by fmarier** [brave/extension-whitelist#48]
https://chrome.google.com/webstore/detail/loc/eojdckfcadamkapabechhbnkleligand

If a user is already logged into Facebook, installing this extension will automatically grant a third-party server access to some of the user's Facebook data. The API used by the extension **does not cause Facebook to show a permission prompt to the user** before the application's access token is issued.

## Details

There is a notice when installing the extension that it will have read & write access to FB and another site:
![Screenshot from 2022-02-04 17-38-22](https://user-images.githubusercontent.com/167821/152623969-46fc7f31-508f-4956-939e-a87b8032ff16.png)

After that, it makes a network call to https://business.facebook.com/creatorstudio/home and ends up creating a new access token without any user interaction:
![Screenshot from 2022-02-04 17-30-55bis](https://user-images.githubusercontent.com/167821/152624199-6a78ba04-ab66-4327-88ed-8ee7a6ebd71c.png)

that's despite the fact that user tokens are supposed to [require an app to ask for permission](https://developers.facebook.com/docs/facebook-login/access-tokens):
> User Access Token: This kind of access token is needed any time the app calls an API to read, modify or write a specific person's Facebook data on their behalf. User access tokens are generally obtained via a login dialog and require a person to permit your app to obtain one.

Interestingly, I can't see that access token anywhere in my account:
![Screenshot from 2022-02-04 17-35-53](https://user-images.githubusercontent.com/167821/152624213-6eb39e7d-a4c4-412c-b1ed-c31ca9659449.png)
![Screenshot from 2022-02-04 17-36-12](https://user-images.githubusercontent.com/167821/152624216-0b3acc3c-3429-4b52-8ac7-75e6037cd621.png)
![Screenshot from 2022-02-04 17-36-24](https://user-images.githubusercontent.com/167821/152624217-d5c9486f-5d7e-4a46-b97f-d18704cdc384.png)

Also, the post-install URL that the extension opens explicitly tells users that their Facebook account might get suspended as a result of installing this extension:
![Screenshot from 2022-02-04 17-31-51](https://user-images.githubusercontent.com/167821/152624271-12b2f50a-86e4-4180-bea7-6df47a15544f.png)

**Comment by fmarier** [comment]
Adding this extension to the `blacklist` section of `extension-whitelist` prevents new installations:
![Screenshot from 2022-02-04 18-23-14](https://user-images.githubusercontent.com/167821/152625593-aac1c8b3-6cc5-4c79-ae2d-99053ccd6d33.png)
and shows a message about already-installed ones:
![Screenshot from 2022-02-04 18-26-05](https://user-images.githubusercontent.com/167821/152625605-76fb064b-e7d1-4bae-94bf-28fda942ca1e.png)
but it's not clear that existing installations are actually disabled:
![Screenshot from 2022-02-04 18-27-01](https://user-images.githubusercontent.com/167821/152625619-e13730ab-8094-4eb4-a079-1bf54aec641d.png)

**Comment by fmarier** [comment]
Blocked as of `Brave Local Data Updater - Version: 1.0.68`.

**Comment by fmarier** [comment]
Announcement up at https://community.brave.com/t/notice-brave-now-blocking-l-o-c-web-extension/340596.

**Comment by locmai0808** [comment]
Hello @fmarier.

I'm the creator of the extension. I would like to verify how my extension would "generate" the access token.
As long as you are logged in on Facebook, if you go to ```view-source:https://business.facebook.com/creatorstudio/home``` on your browser, you should be able to use regex and search for `accessToken` inside there.

![image](https://user-images.githubusercontent.com/18728001/153667302-9fdd8172-c724-4deb-86e8-bd04d4effff3.png)

Based on my report and Facebook's response, it's a "feature" from Facebook and not a bug, so the Access Token from that page is not a bug. 

The extension does not collect user's data unless user becomes a Premium user, and the only thing it collects is UID.

**Comment by fmarier** [comment]
> Based on my report and Facebook's response, it's a "feature" from Facebook and not a bug

Are you able to share this report and Facebook's response? If you prefer not to do it publicly, feel free to email it to me: francois@brave.com

**Comment by locmai0808** [comment]
@fmarier 

> If I understand correctly, you're saying that this Facebook Creators Studio has its own access key that's not visible in a user's settings. The extension then extracts this key from the HTML and then uses it to access the various Facebook APIs it needs. Is that correct? 

Yes this is correct, the access token is within the HTML of that page. Any Facebook user can really just go to `view-source:https://business.facebook.com/creatorstudio/home` and view the access token in there. 

Each Facebook user is assigned with a UID, for example Mark has UID of 4 (fb.com/4)
The extension keeps the access token locally in their browser, and to be excactly, it's stored under `localStorage.touch` 
The extension does NOT send/collect user's Access token to anywhere, everything runs locally.
The extension will collect user UID, and compare with my database to see if the user is a Premium user or not, and thus can allow access to some Premium features. 

I will forward to you my bug report emails - the only copies I have left since I'm banned on Facebook platform forever.
